root = "."
tmp_dir = "tmp"

[build]
pre_cmd = ["cd frontend && bun run build"]
cmd = "go build -o ./tmp/app ./cmd/abyss"
bin = "tmp/app"

[log]
main_only = true

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
