name: abyss

volumes:
  abyss-db-data:

networks:
  abyss-network:

services:
  database:
    image: postgres:17.7-alpine3.22
    environment:
      - POSTGRES_DB=abyss
      - POSTGRES_USER=abyss
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
    volumes:
      - abyss-db-data:/var/lib/postgres
    networks:
      - abyss-network

  abyss:
    image: git.4thena.io/4thena/abyss:latest
    depends_on:
      - database
    environment:
      - ABYSS_DB_TYPE=postgres
      - ABYSS_DB_HOST=database
      - ABYSS_DB_PORT=5432
      - ABYSS_DB_NAME=abyss
      - ABYSS_DB_USER=abyss
      - ABYSS_DB_PASSWORD=123456
    ports:
      - 8000:8000
    networks:
      - abyss-network
