name: Release Abyss

on:
  push:
    tags: ["*"]

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22.17.0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.3

      - name: Install dependencies
        run: |
          cd frontend
          bun install

      - name: Build for production
        run: |
          cd frontend
          bun run build

      - name: Upload frontend artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist

  build-binary:
    name: Build Binary
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - name: Clone the repository
        uses: actions/checkout@v5

      - name: Setup Golang
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Download frontend artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist

      - name: Install XGO
        run: go install src.techknowlogick.com/xgo@latest

      - name: Build final binary
        run: |
          xgo \
          --targets=linux/amd64,linux/arm64 \
          --dest build \
          --out abyss \
          ./cmd/api/main.go

      - name: Upload binary artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: build/

  build-push-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: [build-binary]
    steps:
      - name: Clone the repository
        uses: actions/checkout@v5

      - name: Download binary artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: build/

      - name: Login into registry
        uses: docker/login-action@v3
        with:
          registry: git.4thena.io
          username: ${{ gitea.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          file: Containerfile
          context: .
          tags: |
            git.4thena.io/${{ gitea.repository }}:latest
