CREATE TABLE "main"."apps" (
    "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "name" character varying NOT NULL,
    "description" character varying NOT NULL,
    "kind" character varying,
    "language" character varying,
    "repo_id" bigint NOT NULL,
    "repo_url" character varying NOT NULL,
    "clone_url" character varying NOT NULL,
    "ci_id" bigint NOT NULL,
    "ci_url" character varying NOT NULL,
    "project" character varying NOT NULL,
    "status" "main"."status_enum" NOT NULL DEFAULT 'NEW',
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    CONSTRAINT "pk_app" PRIMARY KEY ("id"),
    CONSTRAINT "uq_app_name" UNIQUE ("name"),
    CONSTRAINT "uq_repo_id" UNIQUE ("repo_id"),
    CONSTRAINT "uq_repo_url" UNIQUE ("repo_url"),
    CONSTRAINT "uq_clone_url" UNIQUE ("clone_url"),
    CONSTRAINT "uq_ci_id" UNIQUE ("ci_id"),
    CONSTRAINT "uq_ci_url" UNIQUE ("ci_url"),
    CONSTRAINT "fk_project" FOREIGN KEY ("project") REFERENCES "main"."projects" ("name")
);
