// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/4thena-io/abyss/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTeamRepository creates a new instance of MockTeamRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamRepository {
	mock := &MockTeamRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTeamRepository is an autogenerated mock type for the TeamRepository type
type MockTeamRepository struct {
	mock.Mock
}

type MockTeamRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamRepository) EXPECT() *MockTeamRepository_Expecter {
	return &MockTeamRepository_Expecter{mock: &_m.Mock}
}

// CountMembers provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) CountMembers(ctx context.Context, teamID uint) (int64, error) {
	ret := _mock.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for CountMembers")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (int64, error)); ok {
		return returnFunc(ctx, teamID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) int64); ok {
		r0 = returnFunc(ctx, teamID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamRepository_CountMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountMembers'
type MockTeamRepository_CountMembers_Call struct {
	*mock.Call
}

// CountMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uint
func (_e *MockTeamRepository_Expecter) CountMembers(ctx any, teamID any) *MockTeamRepository_CountMembers_Call {
	return &MockTeamRepository_CountMembers_Call{Call: _e.mock.On("CountMembers", ctx, teamID)}
}

func (_c *MockTeamRepository_CountMembers_Call) Run(run func(ctx context.Context, teamID uint)) *MockTeamRepository_CountMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamRepository_CountMembers_Call) Return(n int64, err error) *MockTeamRepository_CountMembers_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockTeamRepository_CountMembers_Call) RunAndReturn(run func(ctx context.Context, teamID uint) (int64, error)) *MockTeamRepository_CountMembers_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) Delete(ctx context.Context, team *model.Team) error {
	ret := _mock.Called(ctx, team)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Team) error); ok {
		r0 = returnFunc(ctx, team)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTeamRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTeamRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - team *model.Team
func (_e *MockTeamRepository_Expecter) Delete(ctx any, team any) *MockTeamRepository_Delete_Call {
	return &MockTeamRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, team)}
}

func (_c *MockTeamRepository_Delete_Call) Run(run func(ctx context.Context, team *model.Team)) *MockTeamRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Team
		if args[1] != nil {
			arg1 = args[1].(*model.Team)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamRepository_Delete_Call) Return(err error) *MockTeamRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTeamRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, team *model.Team) error) *MockTeamRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMember provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) DeleteMember(ctx context.Context, teamID uint, memberID uint) error {
	ret := _mock.Called(ctx, teamID, memberID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMember")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = returnFunc(ctx, teamID, memberID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTeamRepository_DeleteMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMember'
type MockTeamRepository_DeleteMember_Call struct {
	*mock.Call
}

// DeleteMember is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uint
//   - memberID uint
func (_e *MockTeamRepository_Expecter) DeleteMember(ctx any, teamID any, memberID any) *MockTeamRepository_DeleteMember_Call {
	return &MockTeamRepository_DeleteMember_Call{Call: _e.mock.On("DeleteMember", ctx, teamID, memberID)}
}

func (_c *MockTeamRepository_DeleteMember_Call) Run(run func(ctx context.Context, teamID uint, memberID uint)) *MockTeamRepository_DeleteMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTeamRepository_DeleteMember_Call) Return(err error) *MockTeamRepository_DeleteMember_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTeamRepository_DeleteMember_Call) RunAndReturn(run func(ctx context.Context, teamID uint, memberID uint) error) *MockTeamRepository_DeleteMember_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) GetAll(ctx context.Context) ([]model.Team, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.Team
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Team, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Team); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Team)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockTeamRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTeamRepository_Expecter) GetAll(ctx any) *MockTeamRepository_GetAll_Call {
	return &MockTeamRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockTeamRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockTeamRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTeamRepository_GetAll_Call) Return(teams []model.Team, err error) *MockTeamRepository_GetAll_Call {
	_c.Call.Return(teams, err)
	return _c
}

func (_c *MockTeamRepository_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]model.Team, error)) *MockTeamRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) GetByID(ctx context.Context, id uint) (*model.Team, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Team
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*model.Team, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *model.Team); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Team)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTeamRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockTeamRepository_Expecter) GetByID(ctx any, id any) *MockTeamRepository_GetByID_Call {
	return &MockTeamRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockTeamRepository_GetByID_Call) Run(run func(ctx context.Context, id uint)) *MockTeamRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamRepository_GetByID_Call) Return(team *model.Team, err error) *MockTeamRepository_GetByID_Call {
	_c.Call.Return(team, err)
	return _c
}

func (_c *MockTeamRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uint) (*model.Team, error)) *MockTeamRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) GetByName(ctx context.Context, name string) (*model.Team, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *model.Team
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Team, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Team); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Team)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamRepository_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockTeamRepository_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockTeamRepository_Expecter) GetByName(ctx any, name any) *MockTeamRepository_GetByName_Call {
	return &MockTeamRepository_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockTeamRepository_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockTeamRepository_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamRepository_GetByName_Call) Return(team *model.Team, err error) *MockTeamRepository_GetByName_Call {
	_c.Call.Return(team, err)
	return _c
}

func (_c *MockTeamRepository_GetByName_Call) RunAndReturn(run func(ctx context.Context, name string) (*model.Team, error)) *MockTeamRepository_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) GetByUserID(ctx context.Context, userID uint) ([]model.TeamMember, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []model.TeamMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]model.TeamMember, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []model.TeamMember); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.TeamMember)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockTeamRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockTeamRepository_Expecter) GetByUserID(ctx any, userID any) *MockTeamRepository_GetByUserID_Call {
	return &MockTeamRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *MockTeamRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID uint)) *MockTeamRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamRepository_GetByUserID_Call) Return(teamMembers []model.TeamMember, err error) *MockTeamRepository_GetByUserID_Call {
	_c.Call.Return(teamMembers, err)
	return _c
}

func (_c *MockTeamRepository_GetByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uint) ([]model.TeamMember, error)) *MockTeamRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMembers provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) GetMembers(ctx context.Context, teamID uint) ([]model.TeamMember, error) {
	ret := _mock.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetMembers")
	}

	var r0 []model.TeamMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]model.TeamMember, error)); ok {
		return returnFunc(ctx, teamID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []model.TeamMember); ok {
		r0 = returnFunc(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.TeamMember)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamRepository_GetMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMembers'
type MockTeamRepository_GetMembers_Call struct {
	*mock.Call
}

// GetMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uint
func (_e *MockTeamRepository_Expecter) GetMembers(ctx any, teamID any) *MockTeamRepository_GetMembers_Call {
	return &MockTeamRepository_GetMembers_Call{Call: _e.mock.On("GetMembers", ctx, teamID)}
}

func (_c *MockTeamRepository_GetMembers_Call) Run(run func(ctx context.Context, teamID uint)) *MockTeamRepository_GetMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamRepository_GetMembers_Call) Return(teamMembers []model.TeamMember, err error) *MockTeamRepository_GetMembers_Call {
	_c.Call.Return(teamMembers, err)
	return _c
}

func (_c *MockTeamRepository_GetMembers_Call) RunAndReturn(run func(ctx context.Context, teamID uint) ([]model.TeamMember, error)) *MockTeamRepository_GetMembers_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) Save(ctx context.Context, team *model.Team) error {
	ret := _mock.Called(ctx, team)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Team) error); ok {
		r0 = returnFunc(ctx, team)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTeamRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockTeamRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - team *model.Team
func (_e *MockTeamRepository_Expecter) Save(ctx any, team any) *MockTeamRepository_Save_Call {
	return &MockTeamRepository_Save_Call{Call: _e.mock.On("Save", ctx, team)}
}

func (_c *MockTeamRepository_Save_Call) Run(run func(ctx context.Context, team *model.Team)) *MockTeamRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Team
		if args[1] != nil {
			arg1 = args[1].(*model.Team)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamRepository_Save_Call) Return(err error) *MockTeamRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTeamRepository_Save_Call) RunAndReturn(run func(ctx context.Context, team *model.Team) error) *MockTeamRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SaveMember provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) SaveMember(ctx context.Context, member *model.TeamMember) error {
	ret := _mock.Called(ctx, member)

	if len(ret) == 0 {
		panic("no return value specified for SaveMember")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.TeamMember) error); ok {
		r0 = returnFunc(ctx, member)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTeamRepository_SaveMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveMember'
type MockTeamRepository_SaveMember_Call struct {
	*mock.Call
}

// SaveMember is a helper method to define mock.On call
//   - ctx context.Context
//   - member *model.TeamMember
func (_e *MockTeamRepository_Expecter) SaveMember(ctx any, member any) *MockTeamRepository_SaveMember_Call {
	return &MockTeamRepository_SaveMember_Call{Call: _e.mock.On("SaveMember", ctx, member)}
}

func (_c *MockTeamRepository_SaveMember_Call) Run(run func(ctx context.Context, member *model.TeamMember)) *MockTeamRepository_SaveMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.TeamMember
		if args[1] != nil {
			arg1 = args[1].(*model.TeamMember)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamRepository_SaveMember_Call) Return(err error) *MockTeamRepository_SaveMember_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTeamRepository_SaveMember_Call) RunAndReturn(run func(ctx context.Context, member *model.TeamMember) error) *MockTeamRepository_SaveMember_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTeamRepository
func (_mock *MockTeamRepository) Update(ctx context.Context, team *model.Team) error {
	ret := _mock.Called(ctx, team)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Team) error); ok {
		r0 = returnFunc(ctx, team)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTeamRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTeamRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - team *model.Team
func (_e *MockTeamRepository_Expecter) Update(ctx any, team any) *MockTeamRepository_Update_Call {
	return &MockTeamRepository_Update_Call{Call: _e.mock.On("Update", ctx, team)}
}

func (_c *MockTeamRepository_Update_Call) Run(run func(ctx context.Context, team *model.Team)) *MockTeamRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Team
		if args[1] != nil {
			arg1 = args[1].(*model.Team)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamRepository_Update_Call) Return(err error) *MockTeamRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTeamRepository_Update_Call) RunAndReturn(run func(ctx context.Context, team *model.Team) error) *MockTeamRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
