// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/4thena-io/abyss/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDeploymentRepository creates a new instance of MockDeploymentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeploymentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeploymentRepository {
	mock := &MockDeploymentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeploymentRepository is an autogenerated mock type for the DeploymentRepository type
type MockDeploymentRepository struct {
	mock.Mock
}

type MockDeploymentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeploymentRepository) EXPECT() *MockDeploymentRepository_Expecter {
	return &MockDeploymentRepository_Expecter{mock: &_m.Mock}
}

// GetByApp provides a mock function for the type MockDeploymentRepository
func (_mock *MockDeploymentRepository) GetByApp(ctx context.Context, appID uint) ([]model.Deployment, error) {
	ret := _mock.Called(ctx, appID)

	if len(ret) == 0 {
		panic("no return value specified for GetByApp")
	}

	var r0 []model.Deployment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]model.Deployment, error)); ok {
		return returnFunc(ctx, appID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []model.Deployment); ok {
		r0 = returnFunc(ctx, appID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Deployment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, appID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeploymentRepository_GetByApp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByApp'
type MockDeploymentRepository_GetByApp_Call struct {
	*mock.Call
}

// GetByApp is a helper method to define mock.On call
//   - ctx context.Context
//   - appID uint
func (_e *MockDeploymentRepository_Expecter) GetByApp(ctx any, appID any) *MockDeploymentRepository_GetByApp_Call {
	return &MockDeploymentRepository_GetByApp_Call{Call: _e.mock.On("GetByApp", ctx, appID)}
}

func (_c *MockDeploymentRepository_GetByApp_Call) Run(run func(ctx context.Context, appID uint)) *MockDeploymentRepository_GetByApp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeploymentRepository_GetByApp_Call) Return(deployments []model.Deployment, err error) *MockDeploymentRepository_GetByApp_Call {
	_c.Call.Return(deployments, err)
	return _c
}

func (_c *MockDeploymentRepository_GetByApp_Call) RunAndReturn(run func(ctx context.Context, appID uint) ([]model.Deployment, error)) *MockDeploymentRepository_GetByApp_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockDeploymentRepository
func (_mock *MockDeploymentRepository) Save(ctx context.Context, deployment *model.Deployment) error {
	ret := _mock.Called(ctx, deployment)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Deployment) error); ok {
		r0 = returnFunc(ctx, deployment)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeploymentRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockDeploymentRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - deployment *model.Deployment
func (_e *MockDeploymentRepository_Expecter) Save(ctx any, deployment any) *MockDeploymentRepository_Save_Call {
	return &MockDeploymentRepository_Save_Call{Call: _e.mock.On("Save", ctx, deployment)}
}

func (_c *MockDeploymentRepository_Save_Call) Run(run func(ctx context.Context, deployment *model.Deployment)) *MockDeploymentRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Deployment
		if args[1] != nil {
			arg1 = args[1].(*model.Deployment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeploymentRepository_Save_Call) Return(err error) *MockDeploymentRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeploymentRepository_Save_Call) RunAndReturn(run func(ctx context.Context, deployment *model.Deployment) error) *MockDeploymentRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
