// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/4thena-io/abyss/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProjectRepository creates a new instance of MockProjectRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectRepository {
	mock := &MockProjectRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProjectRepository is an autogenerated mock type for the ProjectRepository type
type MockProjectRepository struct {
	mock.Mock
}

type MockProjectRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectRepository) EXPECT() *MockProjectRepository_Expecter {
	return &MockProjectRepository_Expecter{mock: &_m.Mock}
}

// CountByTeam provides a mock function for the type MockProjectRepository
func (_mock *MockProjectRepository) CountByTeam(ctx context.Context, teamID uint) (int64, error) {
	ret := _mock.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for CountByTeam")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (int64, error)); ok {
		return returnFunc(ctx, teamID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) int64); ok {
		r0 = returnFunc(ctx, teamID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectRepository_CountByTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByTeam'
type MockProjectRepository_CountByTeam_Call struct {
	*mock.Call
}

// CountByTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uint
func (_e *MockProjectRepository_Expecter) CountByTeam(ctx any, teamID any) *MockProjectRepository_CountByTeam_Call {
	return &MockProjectRepository_CountByTeam_Call{Call: _e.mock.On("CountByTeam", ctx, teamID)}
}

func (_c *MockProjectRepository_CountByTeam_Call) Run(run func(ctx context.Context, teamID uint)) *MockProjectRepository_CountByTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProjectRepository_CountByTeam_Call) Return(n int64, err error) *MockProjectRepository_CountByTeam_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockProjectRepository_CountByTeam_Call) RunAndReturn(run func(ctx context.Context, teamID uint) (int64, error)) *MockProjectRepository_CountByTeam_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockProjectRepository
func (_mock *MockProjectRepository) Delete(ctx context.Context, project *model.Project) error {
	ret := _mock.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Project) error); ok {
		r0 = returnFunc(ctx, project)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProjectRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProjectRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - project *model.Project
func (_e *MockProjectRepository_Expecter) Delete(ctx any, project any) *MockProjectRepository_Delete_Call {
	return &MockProjectRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, project)}
}

func (_c *MockProjectRepository_Delete_Call) Run(run func(ctx context.Context, project *model.Project)) *MockProjectRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Project
		if args[1] != nil {
			arg1 = args[1].(*model.Project)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProjectRepository_Delete_Call) Return(err error) *MockProjectRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProjectRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, project *model.Project) error) *MockProjectRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockProjectRepository
func (_mock *MockProjectRepository) GetAll(ctx context.Context) ([]model.Project, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Project, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Project); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockProjectRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProjectRepository_Expecter) GetAll(ctx any) *MockProjectRepository_GetAll_Call {
	return &MockProjectRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockProjectRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockProjectRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProjectRepository_GetAll_Call) Return(projects []model.Project, err error) *MockProjectRepository_GetAll_Call {
	_c.Call.Return(projects, err)
	return _c
}

func (_c *MockProjectRepository_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]model.Project, error)) *MockProjectRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockProjectRepository
func (_mock *MockProjectRepository) GetByID(ctx context.Context, id uint) (*model.Project, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*model.Project, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *model.Project); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockProjectRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockProjectRepository_Expecter) GetByID(ctx any, id any) *MockProjectRepository_GetByID_Call {
	return &MockProjectRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockProjectRepository_GetByID_Call) Run(run func(ctx context.Context, id uint)) *MockProjectRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProjectRepository_GetByID_Call) Return(project *model.Project, err error) *MockProjectRepository_GetByID_Call {
	_c.Call.Return(project, err)
	return _c
}

func (_c *MockProjectRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uint) (*model.Project, error)) *MockProjectRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function for the type MockProjectRepository
func (_mock *MockProjectRepository) GetByName(ctx context.Context, name string) (*model.Project, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *model.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Project, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Project); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectRepository_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockProjectRepository_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockProjectRepository_Expecter) GetByName(ctx any, name any) *MockProjectRepository_GetByName_Call {
	return &MockProjectRepository_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockProjectRepository_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockProjectRepository_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProjectRepository_GetByName_Call) Return(project *model.Project, err error) *MockProjectRepository_GetByName_Call {
	_c.Call.Return(project, err)
	return _c
}

func (_c *MockProjectRepository_GetByName_Call) RunAndReturn(run func(ctx context.Context, name string) (*model.Project, error)) *MockProjectRepository_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTeam provides a mock function for the type MockProjectRepository
func (_mock *MockProjectRepository) GetByTeam(ctx context.Context, teamID uint) ([]model.Project, error) {
	ret := _mock.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetByTeam")
	}

	var r0 []model.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]model.Project, error)); ok {
		return returnFunc(ctx, teamID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []model.Project); ok {
		r0 = returnFunc(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectRepository_GetByTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTeam'
type MockProjectRepository_GetByTeam_Call struct {
	*mock.Call
}

// GetByTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uint
func (_e *MockProjectRepository_Expecter) GetByTeam(ctx any, teamID any) *MockProjectRepository_GetByTeam_Call {
	return &MockProjectRepository_GetByTeam_Call{Call: _e.mock.On("GetByTeam", ctx, teamID)}
}

func (_c *MockProjectRepository_GetByTeam_Call) Run(run func(ctx context.Context, teamID uint)) *MockProjectRepository_GetByTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProjectRepository_GetByTeam_Call) Return(projects []model.Project, err error) *MockProjectRepository_GetByTeam_Call {
	_c.Call.Return(projects, err)
	return _c
}

func (_c *MockProjectRepository_GetByTeam_Call) RunAndReturn(run func(ctx context.Context, teamID uint) ([]model.Project, error)) *MockProjectRepository_GetByTeam_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockProjectRepository
func (_mock *MockProjectRepository) Save(ctx context.Context, project *model.Project) error {
	ret := _mock.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Project) error); ok {
		r0 = returnFunc(ctx, project)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProjectRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockProjectRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - project *model.Project
func (_e *MockProjectRepository_Expecter) Save(ctx any, project any) *MockProjectRepository_Save_Call {
	return &MockProjectRepository_Save_Call{Call: _e.mock.On("Save", ctx, project)}
}

func (_c *MockProjectRepository_Save_Call) Run(run func(ctx context.Context, project *model.Project)) *MockProjectRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Project
		if args[1] != nil {
			arg1 = args[1].(*model.Project)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProjectRepository_Save_Call) Return(err error) *MockProjectRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProjectRepository_Save_Call) RunAndReturn(run func(ctx context.Context, project *model.Project) error) *MockProjectRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockProjectRepository
func (_mock *MockProjectRepository) Update(ctx context.Context, project *model.Project) error {
	ret := _mock.Called(ctx, project)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Project) error); ok {
		r0 = returnFunc(ctx, project)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProjectRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProjectRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - project *model.Project
func (_e *MockProjectRepository_Expecter) Update(ctx any, project any) *MockProjectRepository_Update_Call {
	return &MockProjectRepository_Update_Call{Call: _e.mock.On("Update", ctx, project)}
}

func (_c *MockProjectRepository_Update_Call) Run(run func(ctx context.Context, project *model.Project)) *MockProjectRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Project
		if args[1] != nil {
			arg1 = args[1].(*model.Project)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProjectRepository_Update_Call) Return(err error) *MockProjectRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProjectRepository_Update_Call) RunAndReturn(run func(ctx context.Context, project *model.Project) error) *MockProjectRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
