// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/4thena-io/abyss/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAppRepository creates a new instance of MockAppRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAppRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAppRepository {
	mock := &MockAppRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAppRepository is an autogenerated mock type for the AppRepository type
type MockAppRepository struct {
	mock.Mock
}

type MockAppRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAppRepository) EXPECT() *MockAppRepository_Expecter {
	return &MockAppRepository_Expecter{mock: &_m.Mock}
}

// CountByTeam provides a mock function for the type MockAppRepository
func (_mock *MockAppRepository) CountByTeam(ctx context.Context, teamID uint) (int64, error) {
	ret := _mock.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for CountByTeam")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (int64, error)); ok {
		return returnFunc(ctx, teamID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) int64); ok {
		r0 = returnFunc(ctx, teamID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppRepository_CountByTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByTeam'
type MockAppRepository_CountByTeam_Call struct {
	*mock.Call
}

// CountByTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID uint
func (_e *MockAppRepository_Expecter) CountByTeam(ctx any, teamID any) *MockAppRepository_CountByTeam_Call {
	return &MockAppRepository_CountByTeam_Call{Call: _e.mock.On("CountByTeam", ctx, teamID)}
}

func (_c *MockAppRepository_CountByTeam_Call) Run(run func(ctx context.Context, teamID uint)) *MockAppRepository_CountByTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAppRepository_CountByTeam_Call) Return(n int64, err error) *MockAppRepository_CountByTeam_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAppRepository_CountByTeam_Call) RunAndReturn(run func(ctx context.Context, teamID uint) (int64, error)) *MockAppRepository_CountByTeam_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockAppRepository
func (_mock *MockAppRepository) Delete(ctx context.Context, app *model.App) error {
	ret := _mock.Called(ctx, app)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.App) error); ok {
		r0 = returnFunc(ctx, app)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAppRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAppRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - app *model.App
func (_e *MockAppRepository_Expecter) Delete(ctx any, app any) *MockAppRepository_Delete_Call {
	return &MockAppRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, app)}
}

func (_c *MockAppRepository_Delete_Call) Run(run func(ctx context.Context, app *model.App)) *MockAppRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.App
		if args[1] != nil {
			arg1 = args[1].(*model.App)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAppRepository_Delete_Call) Return(err error) *MockAppRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAppRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, app *model.App) error) *MockAppRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockAppRepository
func (_mock *MockAppRepository) GetAll(ctx context.Context) ([]model.App, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.App
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.App, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.App); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.App)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockAppRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAppRepository_Expecter) GetAll(ctx any) *MockAppRepository_GetAll_Call {
	return &MockAppRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockAppRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockAppRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAppRepository_GetAll_Call) Return(apps []model.App, err error) *MockAppRepository_GetAll_Call {
	_c.Call.Return(apps, err)
	return _c
}

func (_c *MockAppRepository_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]model.App, error)) *MockAppRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockAppRepository
func (_mock *MockAppRepository) GetByID(ctx context.Context, id uint) (*model.App, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.App
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*model.App, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *model.App); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.App)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockAppRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockAppRepository_Expecter) GetByID(ctx any, id any) *MockAppRepository_GetByID_Call {
	return &MockAppRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockAppRepository_GetByID_Call) Run(run func(ctx context.Context, id uint)) *MockAppRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAppRepository_GetByID_Call) Return(app *model.App, err error) *MockAppRepository_GetByID_Call {
	_c.Call.Return(app, err)
	return _c
}

func (_c *MockAppRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uint) (*model.App, error)) *MockAppRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function for the type MockAppRepository
func (_mock *MockAppRepository) GetByName(ctx context.Context, name string) (*model.App, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *model.App
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.App, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.App); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.App)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppRepository_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockAppRepository_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockAppRepository_Expecter) GetByName(ctx any, name any) *MockAppRepository_GetByName_Call {
	return &MockAppRepository_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockAppRepository_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockAppRepository_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAppRepository_GetByName_Call) Return(app *model.App, err error) *MockAppRepository_GetByName_Call {
	_c.Call.Return(app, err)
	return _c
}

func (_c *MockAppRepository_GetByName_Call) RunAndReturn(run func(ctx context.Context, name string) (*model.App, error)) *MockAppRepository_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetByProject provides a mock function for the type MockAppRepository
func (_mock *MockAppRepository) GetByProject(ctx context.Context, id uint) ([]model.App, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByProject")
	}

	var r0 []model.App
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]model.App, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []model.App); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.App)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppRepository_GetByProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByProject'
type MockAppRepository_GetByProject_Call struct {
	*mock.Call
}

// GetByProject is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockAppRepository_Expecter) GetByProject(ctx any, id any) *MockAppRepository_GetByProject_Call {
	return &MockAppRepository_GetByProject_Call{Call: _e.mock.On("GetByProject", ctx, id)}
}

func (_c *MockAppRepository_GetByProject_Call) Run(run func(ctx context.Context, id uint)) *MockAppRepository_GetByProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAppRepository_GetByProject_Call) Return(apps []model.App, err error) *MockAppRepository_GetByProject_Call {
	_c.Call.Return(apps, err)
	return _c
}

func (_c *MockAppRepository_GetByProject_Call) RunAndReturn(run func(ctx context.Context, id uint) ([]model.App, error)) *MockAppRepository_GetByProject_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTemplate provides a mock function for the type MockAppRepository
func (_mock *MockAppRepository) GetByTemplate(ctx context.Context, id uint) ([]model.App, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByTemplate")
	}

	var r0 []model.App
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]model.App, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []model.App); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.App)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppRepository_GetByTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTemplate'
type MockAppRepository_GetByTemplate_Call struct {
	*mock.Call
}

// GetByTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockAppRepository_Expecter) GetByTemplate(ctx any, id any) *MockAppRepository_GetByTemplate_Call {
	return &MockAppRepository_GetByTemplate_Call{Call: _e.mock.On("GetByTemplate", ctx, id)}
}

func (_c *MockAppRepository_GetByTemplate_Call) Run(run func(ctx context.Context, id uint)) *MockAppRepository_GetByTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAppRepository_GetByTemplate_Call) Return(apps []model.App, err error) *MockAppRepository_GetByTemplate_Call {
	_c.Call.Return(apps, err)
	return _c
}

func (_c *MockAppRepository_GetByTemplate_Call) RunAndReturn(run func(ctx context.Context, id uint) ([]model.App, error)) *MockAppRepository_GetByTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockAppRepository
func (_mock *MockAppRepository) Save(ctx context.Context, app *model.App) error {
	ret := _mock.Called(ctx, app)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.App) error); ok {
		r0 = returnFunc(ctx, app)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAppRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockAppRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - app *model.App
func (_e *MockAppRepository_Expecter) Save(ctx any, app any) *MockAppRepository_Save_Call {
	return &MockAppRepository_Save_Call{Call: _e.mock.On("Save", ctx, app)}
}

func (_c *MockAppRepository_Save_Call) Run(run func(ctx context.Context, app *model.App)) *MockAppRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.App
		if args[1] != nil {
			arg1 = args[1].(*model.App)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAppRepository_Save_Call) Return(err error) *MockAppRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAppRepository_Save_Call) RunAndReturn(run func(ctx context.Context, app *model.App) error) *MockAppRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockAppRepository
func (_mock *MockAppRepository) Update(ctx context.Context, app *model.App) error {
	ret := _mock.Called(ctx, app)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.App) error); ok {
		r0 = returnFunc(ctx, app)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAppRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAppRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - app *model.App
func (_e *MockAppRepository_Expecter) Update(ctx any, app any) *MockAppRepository_Update_Call {
	return &MockAppRepository_Update_Call{Call: _e.mock.On("Update", ctx, app)}
}

func (_c *MockAppRepository_Update_Call) Run(run func(ctx context.Context, app *model.App)) *MockAppRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.App
		if args[1] != nil {
			arg1 = args[1].(*model.App)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAppRepository_Update_Call) Return(err error) *MockAppRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAppRepository_Update_Call) RunAndReturn(run func(ctx context.Context, app *model.App) error) *MockAppRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
