// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/4thena-io/abyss/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTemplateRepository creates a new instance of MockTemplateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTemplateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTemplateRepository {
	mock := &MockTemplateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTemplateRepository is an autogenerated mock type for the TemplateRepository type
type MockTemplateRepository struct {
	mock.Mock
}

type MockTemplateRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTemplateRepository) EXPECT() *MockTemplateRepository_Expecter {
	return &MockTemplateRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockTemplateRepository
func (_mock *MockTemplateRepository) Delete(ctx context.Context, template *model.Template) error {
	ret := _mock.Called(ctx, template)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Template) error); ok {
		r0 = returnFunc(ctx, template)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTemplateRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTemplateRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - template *model.Template
func (_e *MockTemplateRepository_Expecter) Delete(ctx any, template any) *MockTemplateRepository_Delete_Call {
	return &MockTemplateRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, template)}
}

func (_c *MockTemplateRepository_Delete_Call) Run(run func(ctx context.Context, template *model.Template)) *MockTemplateRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Template
		if args[1] != nil {
			arg1 = args[1].(*model.Template)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTemplateRepository_Delete_Call) Return(err error) *MockTemplateRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTemplateRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, template *model.Template) error) *MockTemplateRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockTemplateRepository
func (_mock *MockTemplateRepository) GetAll(ctx context.Context) ([]model.Template, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.Template
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Template, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Template); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Template)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTemplateRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockTemplateRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTemplateRepository_Expecter) GetAll(ctx any) *MockTemplateRepository_GetAll_Call {
	return &MockTemplateRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockTemplateRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockTemplateRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTemplateRepository_GetAll_Call) Return(templates []model.Template, err error) *MockTemplateRepository_GetAll_Call {
	_c.Call.Return(templates, err)
	return _c
}

func (_c *MockTemplateRepository_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]model.Template, error)) *MockTemplateRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockTemplateRepository
func (_mock *MockTemplateRepository) GetByID(ctx context.Context, id uint) (*model.Template, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Template
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*model.Template, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *model.Template); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Template)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTemplateRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTemplateRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockTemplateRepository_Expecter) GetByID(ctx any, id any) *MockTemplateRepository_GetByID_Call {
	return &MockTemplateRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockTemplateRepository_GetByID_Call) Run(run func(ctx context.Context, id uint)) *MockTemplateRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTemplateRepository_GetByID_Call) Return(template *model.Template, err error) *MockTemplateRepository_GetByID_Call {
	_c.Call.Return(template, err)
	return _c
}

func (_c *MockTemplateRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uint) (*model.Template, error)) *MockTemplateRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function for the type MockTemplateRepository
func (_mock *MockTemplateRepository) GetByName(ctx context.Context, name string) (*model.Template, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *model.Template
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Template, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Template); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Template)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTemplateRepository_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockTemplateRepository_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockTemplateRepository_Expecter) GetByName(ctx any, name any) *MockTemplateRepository_GetByName_Call {
	return &MockTemplateRepository_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockTemplateRepository_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockTemplateRepository_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTemplateRepository_GetByName_Call) Return(template *model.Template, err error) *MockTemplateRepository_GetByName_Call {
	_c.Call.Return(template, err)
	return _c
}

func (_c *MockTemplateRepository_GetByName_Call) RunAndReturn(run func(ctx context.Context, name string) (*model.Template, error)) *MockTemplateRepository_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockTemplateRepository
func (_mock *MockTemplateRepository) Save(ctx context.Context, template *model.Template) error {
	ret := _mock.Called(ctx, template)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Template) error); ok {
		r0 = returnFunc(ctx, template)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTemplateRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockTemplateRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - template *model.Template
func (_e *MockTemplateRepository_Expecter) Save(ctx any, template any) *MockTemplateRepository_Save_Call {
	return &MockTemplateRepository_Save_Call{Call: _e.mock.On("Save", ctx, template)}
}

func (_c *MockTemplateRepository_Save_Call) Run(run func(ctx context.Context, template *model.Template)) *MockTemplateRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Template
		if args[1] != nil {
			arg1 = args[1].(*model.Template)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTemplateRepository_Save_Call) Return(err error) *MockTemplateRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTemplateRepository_Save_Call) RunAndReturn(run func(ctx context.Context, template *model.Template) error) *MockTemplateRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTemplateRepository
func (_mock *MockTemplateRepository) Update(ctx context.Context, template *model.Template) error {
	ret := _mock.Called(ctx, template)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Template) error); ok {
		r0 = returnFunc(ctx, template)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTemplateRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTemplateRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - template *model.Template
func (_e *MockTemplateRepository_Expecter) Update(ctx any, template any) *MockTemplateRepository_Update_Call {
	return &MockTemplateRepository_Update_Call{Call: _e.mock.On("Update", ctx, template)}
}

func (_c *MockTemplateRepository_Update_Call) Run(run func(ctx context.Context, template *model.Template)) *MockTemplateRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Template
		if args[1] != nil {
			arg1 = args[1].(*model.Template)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTemplateRepository_Update_Call) Return(err error) *MockTemplateRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTemplateRepository_Update_Call) RunAndReturn(run func(ctx context.Context, template *model.Template) error) *MockTemplateRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
