// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/4thena-io/abyss/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockForge creates a new instance of MockForge. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockForge(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockForge {
	mock := &MockForge{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockForge is an autogenerated mock type for the Forge type
type MockForge struct {
	mock.Mock
}

type MockForge_Expecter struct {
	mock *mock.Mock
}

func (_m *MockForge) EXPECT() *MockForge_Expecter {
	return &MockForge_Expecter{mock: &_m.Mock}
}

// CreateRepo provides a mock function for the type MockForge
func (_mock *MockForge) CreateRepo(ctx context.Context, owner string, name string) (*model.Repo, error) {
	ret := _mock.Called(ctx, owner, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateRepo")
	}

	var r0 *model.Repo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.Repo, error)); ok {
		return returnFunc(ctx, owner, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.Repo); ok {
		r0 = returnFunc(ctx, owner, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Repo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, owner, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockForge_CreateRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRepo'
type MockForge_CreateRepo_Call struct {
	*mock.Call
}

// CreateRepo is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - name string
func (_e *MockForge_Expecter) CreateRepo(ctx any, owner any, name any) *MockForge_CreateRepo_Call {
	return &MockForge_CreateRepo_Call{Call: _e.mock.On("CreateRepo", ctx, owner, name)}
}

func (_c *MockForge_CreateRepo_Call) Run(run func(ctx context.Context, owner string, name string)) *MockForge_CreateRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockForge_CreateRepo_Call) Return(repo *model.Repo, err error) *MockForge_CreateRepo_Call {
	_c.Call.Return(repo, err)
	return _c
}

func (_c *MockForge_CreateRepo_Call) RunAndReturn(run func(ctx context.Context, owner string, name string) (*model.Repo, error)) *MockForge_CreateRepo_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWebhook provides a mock function for the type MockForge
func (_mock *MockForge) CreateWebhook(ctx context.Context, owner string, repo string, callbackURL string, secret string, branch string) error {
	ret := _mock.Called(ctx, owner, repo, callbackURL, secret, branch)

	if len(ret) == 0 {
		panic("no return value specified for CreateWebhook")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, owner, repo, callbackURL, secret, branch)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockForge_CreateWebhook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWebhook'
type MockForge_CreateWebhook_Call struct {
	*mock.Call
}

// CreateWebhook is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - callbackURL string
//   - secret string
//   - branch string
func (_e *MockForge_Expecter) CreateWebhook(ctx any, owner any, repo any, callbackURL any, secret any, branch any) *MockForge_CreateWebhook_Call {
	return &MockForge_CreateWebhook_Call{Call: _e.mock.On("CreateWebhook", ctx, owner, repo, callbackURL, secret, branch)}
}

func (_c *MockForge_CreateWebhook_Call) Run(run func(ctx context.Context, owner string, repo string, callbackURL string, secret string, branch string)) *MockForge_CreateWebhook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockForge_CreateWebhook_Call) Return(err error) *MockForge_CreateWebhook_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockForge_CreateWebhook_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, callbackURL string, secret string, branch string) error) *MockForge_CreateWebhook_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRepo provides a mock function for the type MockForge
func (_mock *MockForge) DeleteRepo(ctx context.Context, owner string, name string) error {
	ret := _mock.Called(ctx, owner, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRepo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, owner, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockForge_DeleteRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRepo'
type MockForge_DeleteRepo_Call struct {
	*mock.Call
}

// DeleteRepo is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - name string
func (_e *MockForge_Expecter) DeleteRepo(ctx any, owner any, name any) *MockForge_DeleteRepo_Call {
	return &MockForge_DeleteRepo_Call{Call: _e.mock.On("DeleteRepo", ctx, owner, name)}
}

func (_c *MockForge_DeleteRepo_Call) Run(run func(ctx context.Context, owner string, name string)) *MockForge_DeleteRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockForge_DeleteRepo_Call) Return(err error) *MockForge_DeleteRepo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockForge_DeleteRepo_Call) RunAndReturn(run func(ctx context.Context, owner string, name string) error) *MockForge_DeleteRepo_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWebhook provides a mock function for the type MockForge
func (_mock *MockForge) DeleteWebhook(ctx context.Context, owner string, repo string, callbackURL string) error {
	ret := _mock.Called(ctx, owner, repo, callbackURL)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWebhook")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, owner, repo, callbackURL)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockForge_DeleteWebhook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWebhook'
type MockForge_DeleteWebhook_Call struct {
	*mock.Call
}

// DeleteWebhook is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - callbackURL string
func (_e *MockForge_Expecter) DeleteWebhook(ctx any, owner any, repo any, callbackURL any) *MockForge_DeleteWebhook_Call {
	return &MockForge_DeleteWebhook_Call{Call: _e.mock.On("DeleteWebhook", ctx, owner, repo, callbackURL)}
}

func (_c *MockForge_DeleteWebhook_Call) Run(run func(ctx context.Context, owner string, repo string, callbackURL string)) *MockForge_DeleteWebhook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockForge_DeleteWebhook_Call) Return(err error) *MockForge_DeleteWebhook_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockForge_DeleteWebhook_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, callbackURL string) error) *MockForge_DeleteWebhook_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthenticatedUser provides a mock function for the type MockForge
func (_mock *MockForge) GetAuthenticatedUser(ctx context.Context) (*model.ForgeUser, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthenticatedUser")
	}

	var r0 *model.ForgeUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*model.ForgeUser, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *model.ForgeUser); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ForgeUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockForge_GetAuthenticatedUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthenticatedUser'
type MockForge_GetAuthenticatedUser_Call struct {
	*mock.Call
}

// GetAuthenticatedUser is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockForge_Expecter) GetAuthenticatedUser(ctx any) *MockForge_GetAuthenticatedUser_Call {
	return &MockForge_GetAuthenticatedUser_Call{Call: _e.mock.On("GetAuthenticatedUser", ctx)}
}

func (_c *MockForge_GetAuthenticatedUser_Call) Run(run func(ctx context.Context)) *MockForge_GetAuthenticatedUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockForge_GetAuthenticatedUser_Call) Return(forgeUser *model.ForgeUser, err error) *MockForge_GetAuthenticatedUser_Call {
	_c.Call.Return(forgeUser, err)
	return _c
}

func (_c *MockForge_GetAuthenticatedUser_Call) RunAndReturn(run func(ctx context.Context) (*model.ForgeUser, error)) *MockForge_GetAuthenticatedUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrgRepos provides a mock function for the type MockForge
func (_mock *MockForge) GetOrgRepos(ctx context.Context, name string) ([]model.Repo, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetOrgRepos")
	}

	var r0 []model.Repo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]model.Repo, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []model.Repo); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Repo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockForge_GetOrgRepos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrgRepos'
type MockForge_GetOrgRepos_Call struct {
	*mock.Call
}

// GetOrgRepos is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockForge_Expecter) GetOrgRepos(ctx any, name any) *MockForge_GetOrgRepos_Call {
	return &MockForge_GetOrgRepos_Call{Call: _e.mock.On("GetOrgRepos", ctx, name)}
}

func (_c *MockForge_GetOrgRepos_Call) Run(run func(ctx context.Context, name string)) *MockForge_GetOrgRepos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockForge_GetOrgRepos_Call) Return(repos []model.Repo, err error) *MockForge_GetOrgRepos_Call {
	_c.Call.Return(repos, err)
	return _c
}

func (_c *MockForge_GetOrgRepos_Call) RunAndReturn(run func(ctx context.Context, name string) ([]model.Repo, error)) *MockForge_GetOrgRepos_Call {
	_c.Call.Return(run)
	return _c
}

// GetRepo provides a mock function for the type MockForge
func (_mock *MockForge) GetRepo(ctx context.Context, id int64) (*model.Repo, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRepo")
	}

	var r0 *model.Repo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*model.Repo, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *model.Repo); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Repo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockForge_GetRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepo'
type MockForge_GetRepo_Call struct {
	*mock.Call
}

// GetRepo is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockForge_Expecter) GetRepo(ctx any, id any) *MockForge_GetRepo_Call {
	return &MockForge_GetRepo_Call{Call: _e.mock.On("GetRepo", ctx, id)}
}

func (_c *MockForge_GetRepo_Call) Run(run func(ctx context.Context, id int64)) *MockForge_GetRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockForge_GetRepo_Call) Return(repo *model.Repo, err error) *MockForge_GetRepo_Call {
	_c.Call.Return(repo, err)
	return _c
}

func (_c *MockForge_GetRepo_Call) RunAndReturn(run func(ctx context.Context, id int64) (*model.Repo, error)) *MockForge_GetRepo_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByToken provides a mock function for the type MockForge
func (_mock *MockForge) GetUserByToken(ctx context.Context, token string) (*model.ForgeUser, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByToken")
	}

	var r0 *model.ForgeUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.ForgeUser, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.ForgeUser); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ForgeUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockForge_GetUserByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByToken'
type MockForge_GetUserByToken_Call struct {
	*mock.Call
}

// GetUserByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockForge_Expecter) GetUserByToken(ctx any, token any) *MockForge_GetUserByToken_Call {
	return &MockForge_GetUserByToken_Call{Call: _e.mock.On("GetUserByToken", ctx, token)}
}

func (_c *MockForge_GetUserByToken_Call) Run(run func(ctx context.Context, token string)) *MockForge_GetUserByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockForge_GetUserByToken_Call) Return(forgeUser *model.ForgeUser, err error) *MockForge_GetUserByToken_Call {
	_c.Call.Return(forgeUser, err)
	return _c
}

func (_c *MockForge_GetUserByToken_Call) RunAndReturn(run func(ctx context.Context, token string) (*model.ForgeUser, error)) *MockForge_GetUserByToken_Call {
	_c.Call.Return(run)
	return _c
}

// IsMemberOfOwner provides a mock function for the type MockForge
func (_mock *MockForge) IsMemberOfOwner(ctx context.Context, owner string, username string) (bool, error) {
	ret := _mock.Called(ctx, owner, username)

	if len(ret) == 0 {
		panic("no return value specified for IsMemberOfOwner")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, owner, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, owner, username)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, owner, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockForge_IsMemberOfOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsMemberOfOwner'
type MockForge_IsMemberOfOwner_Call struct {
	*mock.Call
}

// IsMemberOfOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - username string
func (_e *MockForge_Expecter) IsMemberOfOwner(ctx any, owner any, username any) *MockForge_IsMemberOfOwner_Call {
	return &MockForge_IsMemberOfOwner_Call{Call: _e.mock.On("IsMemberOfOwner", ctx, owner, username)}
}

func (_c *MockForge_IsMemberOfOwner_Call) Run(run func(ctx context.Context, owner string, username string)) *MockForge_IsMemberOfOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockForge_IsMemberOfOwner_Call) Return(b bool, err error) *MockForge_IsMemberOfOwner_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockForge_IsMemberOfOwner_Call) RunAndReturn(run func(ctx context.Context, owner string, username string) (bool, error)) *MockForge_IsMemberOfOwner_Call {
	_c.Call.Return(run)
	return _c
}

// OAuthEndpoints provides a mock function for the type MockForge
func (_mock *MockForge) OAuthEndpoints() (string, string) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for OAuthEndpoints")
	}

	var r0 string
	var r1 string
	if returnFunc, ok := ret.Get(0).(func() (string, string)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() string); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(string)
	}
	return r0, r1
}

// MockForge_OAuthEndpoints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OAuthEndpoints'
type MockForge_OAuthEndpoints_Call struct {
	*mock.Call
}

// OAuthEndpoints is a helper method to define mock.On call
func (_e *MockForge_Expecter) OAuthEndpoints() *MockForge_OAuthEndpoints_Call {
	return &MockForge_OAuthEndpoints_Call{Call: _e.mock.On("OAuthEndpoints")}
}

func (_c *MockForge_OAuthEndpoints_Call) Run(run func()) *MockForge_OAuthEndpoints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockForge_OAuthEndpoints_Call) Return(authPath string, tokenPath string) *MockForge_OAuthEndpoints_Call {
	_c.Call.Return(authPath, tokenPath)
	return _c
}

func (_c *MockForge_OAuthEndpoints_Call) RunAndReturn(run func() (string, string)) *MockForge_OAuthEndpoints_Call {
	_c.Call.Return(run)
	return _c
}
