// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/4thena-io/abyss/internal/auth"
	"github.com/4thena-io/abyss/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthProvider creates a new instance of MockAuthProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthProvider {
	mock := &MockAuthProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthProvider is an autogenerated mock type for the AuthProvider type
type MockAuthProvider struct {
	mock.Mock
}

type MockAuthProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthProvider) EXPECT() *MockAuthProvider_Expecter {
	return &MockAuthProvider_Expecter{mock: &_m.Mock}
}

// GetUserByToken provides a mock function for the type MockAuthProvider
func (_mock *MockAuthProvider) GetUserByToken(ctx context.Context, token string) (*model.User, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByToken")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthProvider_GetUserByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByToken'
type MockAuthProvider_GetUserByToken_Call struct {
	*mock.Call
}

// GetUserByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockAuthProvider_Expecter) GetUserByToken(ctx any, token any) *MockAuthProvider_GetUserByToken_Call {
	return &MockAuthProvider_GetUserByToken_Call{Call: _e.mock.On("GetUserByToken", ctx, token)}
}

func (_c *MockAuthProvider_GetUserByToken_Call) Run(run func(ctx context.Context, token string)) *MockAuthProvider_GetUserByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthProvider_GetUserByToken_Call) Return(user *model.User, err error) *MockAuthProvider_GetUserByToken_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthProvider_GetUserByToken_Call) RunAndReturn(run func(ctx context.Context, token string) (*model.User, error)) *MockAuthProvider_GetUserByToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateJWT provides a mock function for the type MockAuthProvider
func (_mock *MockAuthProvider) ValidateJWT(tokenStr string) (*auth.Claims, error) {
	ret := _mock.Called(tokenStr)

	if len(ret) == 0 {
		panic("no return value specified for ValidateJWT")
	}

	var r0 *auth.Claims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*auth.Claims, error)); ok {
		return returnFunc(tokenStr)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *auth.Claims); ok {
		r0 = returnFunc(tokenStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Claims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenStr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthProvider_ValidateJWT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateJWT'
type MockAuthProvider_ValidateJWT_Call struct {
	*mock.Call
}

// ValidateJWT is a helper method to define mock.On call
//   - tokenStr string
func (_e *MockAuthProvider_Expecter) ValidateJWT(tokenStr any) *MockAuthProvider_ValidateJWT_Call {
	return &MockAuthProvider_ValidateJWT_Call{Call: _e.mock.On("ValidateJWT", tokenStr)}
}

func (_c *MockAuthProvider_ValidateJWT_Call) Run(run func(tokenStr string)) *MockAuthProvider_ValidateJWT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthProvider_ValidateJWT_Call) Return(claims *auth.Claims, err error) *MockAuthProvider_ValidateJWT_Call {
	_c.Call.Return(claims, err)
	return _c
}

func (_c *MockAuthProvider_ValidateJWT_Call) RunAndReturn(run func(tokenStr string) (*auth.Claims, error)) *MockAuthProvider_ValidateJWT_Call {
	_c.Call.Return(run)
	return _c
}
