when:
  event: push
  branch: feat/*

variables:
  - &golang-image "golang:1.26.2-alpine3.22"
  - &bun-image "oven/bun:1.3.3-alpine"

steps:
  install-ui-dependencies:
    image: *bun-image
    directory: frontend/
    commands:
      - bun install --frozen-lockfile

  build-ui:
    image: *bun-image
    directory: frontend/
    depends_on:
      - install-ui-dependencies
    commands:
      - bun run build

  vendor:
    image: *golang-image
    commands:
      - go mod vendor

  build-binary:
    image: *golang-image
    depends_on:
      - build-ui
      - vendor
    commands:
      - go build -ldflags="-s -w" -o build/abyss .
