when:
  event: tag
  branch: main

variables:
  - &golang-image "golang:1.26.2-alpine3.22"
  - &bun-image "oven/bun:1.3.3-alpine"

matrix:
  os:
    - linux
  arch:
    - amd64
    - arm64

steps:
  install-ui-dependencies:
    image: *bun-image
    directory: frontend/
    commands:
      - bun install --frozen-lockfile

  build-ui:
    image: *bun-image
    directory: frontend/
    depends_on:
      - install-ui-dependencies
    commands:
      - bun run build

  vendor:
    image: *golang-image
    commands:
      - go mod vendor

  build-binary:
    image: *golang-image
    environment:
      CGO_ENABLED: 0
      GOOS: ${os}
      GOARCH: ${arch}
    depends_on:
      - build-ui
      - vendor
    commands:
      - go build -ldflags="-s -w" -o build/abyss-${os}-${arch} .

  build-docker:
    depends_on:
      - build-binary
    image: woodpeckerci/plugin-docker-buildx:6.1.0
    settings:
      registry: git.internal.4thena.io
      repo: "git.internal.4thena.io/${CI_REPO}"
      platforms: linux/amd64,linux/arm64/v8
      tags: "${CI_COMMIT_TAG},latest"
      dockerfile: Containerfile
      username:
        from_secret: REGISTRY_USERNAME
      password:
        from_secret: REGISTRY_TOKEN
