// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/4thena-io/abyss/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCI creates a new instance of MockCI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCI {
	mock := &MockCI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCI is an autogenerated mock type for the CI type
type MockCI struct {
	mock.Mock
}

type MockCI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCI) EXPECT() *MockCI_Expecter {
	return &MockCI_Expecter{mock: &_m.Mock}
}

// ActivateRepo provides a mock function for the type MockCI
func (_mock *MockCI) ActivateRepo(ctx context.Context, forgeRemoteID int64, slug string) (*model.CIRepo, error) {
	ret := _mock.Called(ctx, forgeRemoteID, slug)

	if len(ret) == 0 {
		panic("no return value specified for ActivateRepo")
	}

	var r0 *model.CIRepo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) (*model.CIRepo, error)); ok {
		return returnFunc(ctx, forgeRemoteID, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) *model.CIRepo); ok {
		r0 = returnFunc(ctx, forgeRemoteID, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CIRepo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = returnFunc(ctx, forgeRemoteID, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCI_ActivateRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActivateRepo'
type MockCI_ActivateRepo_Call struct {
	*mock.Call
}

// ActivateRepo is a helper method to define mock.On call
//   - ctx context.Context
//   - forgeRemoteID int64
//   - slug string
func (_e *MockCI_Expecter) ActivateRepo(ctx any, forgeRemoteID any, slug any) *MockCI_ActivateRepo_Call {
	return &MockCI_ActivateRepo_Call{Call: _e.mock.On("ActivateRepo", ctx, forgeRemoteID, slug)}
}

func (_c *MockCI_ActivateRepo_Call) Run(run func(ctx context.Context, forgeRemoteID int64, slug string)) *MockCI_ActivateRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCI_ActivateRepo_Call) Return(cIRepo *model.CIRepo, err error) *MockCI_ActivateRepo_Call {
	_c.Call.Return(cIRepo, err)
	return _c
}

func (_c *MockCI_ActivateRepo_Call) RunAndReturn(run func(ctx context.Context, forgeRemoteID int64, slug string) (*model.CIRepo, error)) *MockCI_ActivateRepo_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRepo provides a mock function for the type MockCI
func (_mock *MockCI) DeleteRepo(ctx context.Context, ciRepoID int64, slug string) error {
	ret := _mock.Called(ctx, ciRepoID, slug)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRepo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, ciRepoID, slug)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCI_DeleteRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRepo'
type MockCI_DeleteRepo_Call struct {
	*mock.Call
}

// DeleteRepo is a helper method to define mock.On call
//   - ctx context.Context
//   - ciRepoID int64
//   - slug string
func (_e *MockCI_Expecter) DeleteRepo(ctx any, ciRepoID any, slug any) *MockCI_DeleteRepo_Call {
	return &MockCI_DeleteRepo_Call{Call: _e.mock.On("DeleteRepo", ctx, ciRepoID, slug)}
}

func (_c *MockCI_DeleteRepo_Call) Run(run func(ctx context.Context, ciRepoID int64, slug string)) *MockCI_DeleteRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCI_DeleteRepo_Call) Return(err error) *MockCI_DeleteRepo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCI_DeleteRepo_Call) RunAndReturn(run func(ctx context.Context, ciRepoID int64, slug string) error) *MockCI_DeleteRepo_Call {
	_c.Call.Return(run)
	return _c
}

// GetBuilds provides a mock function for the type MockCI
func (_mock *MockCI) GetBuilds(ctx context.Context, ciRepoID int64, slug string) ([]model.Build, error) {
	ret := _mock.Called(ctx, ciRepoID, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetBuilds")
	}

	var r0 []model.Build
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) ([]model.Build, error)); ok {
		return returnFunc(ctx, ciRepoID, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) []model.Build); ok {
		r0 = returnFunc(ctx, ciRepoID, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Build)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = returnFunc(ctx, ciRepoID, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCI_GetBuilds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBuilds'
type MockCI_GetBuilds_Call struct {
	*mock.Call
}

// GetBuilds is a helper method to define mock.On call
//   - ctx context.Context
//   - ciRepoID int64
//   - slug string
func (_e *MockCI_Expecter) GetBuilds(ctx any, ciRepoID any, slug any) *MockCI_GetBuilds_Call {
	return &MockCI_GetBuilds_Call{Call: _e.mock.On("GetBuilds", ctx, ciRepoID, slug)}
}

func (_c *MockCI_GetBuilds_Call) Run(run func(ctx context.Context, ciRepoID int64, slug string)) *MockCI_GetBuilds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCI_GetBuilds_Call) Return(builds []model.Build, err error) *MockCI_GetBuilds_Call {
	_c.Call.Return(builds, err)
	return _c
}

func (_c *MockCI_GetBuilds_Call) RunAndReturn(run func(ctx context.Context, ciRepoID int64, slug string) ([]model.Build, error)) *MockCI_GetBuilds_Call {
	_c.Call.Return(run)
	return _c
}
