name: Release Abyss

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build binary
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        uses: actions/checkout@v5

      - name: Setup Golang
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: make deps

      - name: Build the binary
        run: make build

      - name: Setup Docker QEMU agent
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v5

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: Containerfile
          push: true
