name: Release Abyss

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build binary
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          check-latest: true
      - uses: oven-sh/setup-bun@v2
      - run: make deps
      - run: make build
  create-container:
    name: Build and push Docker container
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v5
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
